// <auto-generated />
namespace Resume.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class typeaddtoprojecttype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(typeaddtoprojecttype));
        
        string IMigrationMetadata.Id
        {
            get { return "201912270728467_typeaddtoprojecttype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
