// <auto-generated />
namespace Resume.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class rightsidedeletefromprojectmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rightsidedeletefromprojectmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201912271229150_rightsidedeletefromprojectmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
